### ISSUE TITLE
Disable "More Cards" button

### ISSUE THREAD

**Issue by kovtun1** [foritari/Assigment2#3]
> 10. The Deal 3 More Cards button should be disabled if there are a) no more cards in the Set deck or b) no more room in the UI to fit 3 more cards (note that there is always room for 3 more cards if the 3 currently-selected cards are a match since you replace them).

The button doesn't work, but it should also appear disabled

**Comment by foritari** [comment]
https://github.com/foritari/Assigment2/pull/10
