### ISSUE TITLE
Fix cards layout

### ISSUE THREAD

**Issue by kovtun1** [foritari/Assigment2#7]
Steps to reproduce:
- Tap "New Game"
- Tap "More Cards" until there are no more cards left in the deck
- Tap "Cheat"
- Select highlighted cards
- Tap "Cheat"
- Select highlighted cards
- Tap "Cheat"
- Select highlighted cards
- The cards' layout will animate, but now it is overlapping with the buttons

**Comment by foritari** [comment]
https://github.com/foritari/Assigment2/pull/8 PR for issue.
